fix: Remove install check

diff --git a/modules/consul/consul-terraform-sync/install-consul-terraform-sync b/modules/consul/consul-terraform-sync/install-consul-terraform-sync
--- a/modules/consul/consul-terraform-sync/install-consul-terraform-sync
+++ b/modules/consul/consul-terraform-sync/install-consul-terraform-sync
@@ -285,11 +285,11 @@ function install {
 
   # This command is run with sudo rights so that it will succeed in cases where image hardening alters the permissions
   # on the directories where Consul-Terraform-Sync may be installed.
-  if sudo -E PATH=$PATH bash -c "command -version consul-terraform-sync"; then
-    log_info "Consul-Terraform-Sync install complete!";
-  else
-    log_info "Could not find consul-terraform-sync command. Aborting.";
-    exit 1;
+#  if sudo -E PATH=$PATH bash -c "command -version consul-terraform-sync"; then
+#    log_info "Consul-Terraform-Sync install complete!";
+#  else
+#    log_info "Could not find consul-terraform-sync command. Aborting.";
+#    exit 1;
   fi
 }
 
