test: Remove verify install

diff --git a/examples/scripts/install-boundary b/examples/scripts/install-boundary
--- a/examples/scripts/install-boundary
+++ b/examples/scripts/install-boundary
@@ -287,12 +287,12 @@ function install {
 
   # This command is run with sudo rights so that it will succeed in cases where image hardening alters the permissions
   # on the directories where Boundary may be installed.
-  if sudo -E PATH=$PATH bash -c "command boundary"; then
-    log_info "Boundary install complete!";
-  else
-    log_info "Could not find boundary command. Aborting.";
-    exit 1;
-  fi
+#  if sudo -E PATH=$PATH bash -c "command boundary"; then
+#    log_info "Boundary install complete!";
+#  else
+#    log_info "Could not find boundary command. Aborting.";
+#    exit 1;
+#  fi
 }
 
 install "$@"
